n1 = (float(input("Digite a nota 1: ")))
n2 = (float(input("Digite a nota 2: ")))
n3 = (float(input("Digite a nota 3: ")))
peso1 = ((n1)*0.2)
peso2 = ((n2)*0.4)
peso3 = ((n3)*0.5)
media = ((peso1+peso2+peso3)/3)
print ("A media com peso e:",(media))