sacoRacao = float(input("Fala Pedro!Coloque aqui a quantidade de peso que tem no saco de ração: "))
quantidadeRacao = float(input("Agora Pedrão coloque a quantidade de ração fornecida para os gatos: "))
calculo = ((sacoRacao * 1000)(quantidadeRacao*5))
calculo = (sacoRacao - quantidadeRacao)
print("Vai sobrar Pedro : ",calculo)